sdkversion: "4.0.0"
name: "GeoLocation-Testing"
version: "1.0"
vendor: "rhomobile"
build: "debug"
bbver: "6.0"
applog: "rholog.txt"
iphone:
  configuration: "Release"
  sdk: "iphonesimulator6.0"
  provisionprofile: 
  codesignidentity: 
  entitlements: 
  BundleIdentifier: "com.rhomobile.geolocation-testing"
  BundleURLScheme: "geolocation-testing"
wp:
  productid: "c664f820-4eb4-0131-427a-589d67d0f6ef"
symbian:
  uid: "0xe9178dc5"
android:
  version: "2.3.3"
extensions:
  - rhoconnect-client
app_type: "rhoelements"
capabilities:
  - gps
